using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using Avalonia.Themes.Fluent;
using Avalonia.Threading;
using Avalonia.Styling;

class Program {
 [STAThread] public static void Main(string[] args) => AppBuilder.Configure<App>().UsePlatformDetect().WithInterFont().StartWithClassicDesktopLifetime(args);
}
class App : Application {
 public override void Initialize() { Styles.Add(new FluentTheme()); RequestedThemeVariant=ThemeVariant.Light; }
 public override void OnFrameworkInitializationCompleted() { if(ApplicationLifetime is IClassicDesktopStyleApplicationLifetime d) d.MainWindow=new Atelier(); base.OnFrameworkInitializationCompleted(); }
}
class Atelier : Window {
 static readonly Dictionary<string,SolidColorBrush> palette=new();
 static bool dark;
 Window? toolWindow; ComboBox? themeSelector;
 Button? themeButton;
 static readonly Dictionary<string,string> night=new(){["#30333C"]="#E2E4EB",["#83868F"]="#A0A5B4",["#AD4D53"]="#C4717B",["#F7F7F9"]="#191B22",["#E4E5E9"]="#343743",["#FFFFFF"]="#22252E",["#FBFBFC"]="#292D37",["#F5E8EA"]="#403039",["#B66A73"]="#C4717B",["#CDD0D8"]="#555B6C",["#C0C1C8"]="#666D7E",["#52836C"]="#8EC4A7"};
 const string Ink="#30333C", Muted="#83868F", Accent="#AD4D53", Paper="#F7F7F9", Line="#E4E5E9";
 readonly Grid slots=new(){ColumnDefinitions=new("*,*,*,*,*,*"),RowDefinitions=new("*,*,*,*,*")};
 readonly StackPanel form=new(){Spacing=9};
 readonly TextBlock name=T("Gardevoir",22,Ink,true), number=T("#0282 · Embrace Pokémon",10,Muted), status=T("Concept preview · Sample data",10,Muted);
 readonly Image portrait=Art(282,76);
 readonly TextBlock types=T("PSYCHIC   /   FAIRY",9,Accent,true);
 readonly (int id,string name,int level)[] mons=[(282,"Gardevoir",72),(6,"Charizard",84),(658,"Greninja",78),(448,"Lucario",76),(700,"Sylveon",68),(149,"Dragonite",81),(25,"Pikachu",56),(196,"Espeon",64),(197,"Umbreon",64),(470,"Leafeon",62),(471,"Glaceon",62),(133,"Eevee",24),(94,"Gengar",75),(778,"Mimikyu",58),(38,"Ninetales",66),(59,"Arcanine",71),(350,"Milotic",70),(359,"Absol",65),(373,"Salamence",80),(445,"Garchomp",82),(376,"Metagross",79),(248,"Tyranitar",80),(468,"Togekiss",69),(407,"Roserade",67)];
 int selected; string tab="Main";
 public Atelier(){
 Title="PKHeX · Compact concept";Width=900;Height=600;MinWidth=840;MinHeight=580;Background=B(Paper);FontFamily=new("Inter");Foreground=B(Ink);WindowStartupLocation=WindowStartupLocation.CenterScreen;
 var root=new Grid{Background=B(Paper),RowDefinitions=new("35,49,*,27")};Content=root;
 var menu=new Grid{ColumnDefinitions=new("Auto,*,Auto"),Background=B("#FFFFFF")};Put(menu,new Border{Width=22,Height=22,Background=B(Accent),CornerRadius=new(7),Margin=new(14,0,16,0),Child=new TextBlock{Text="◉",Foreground=Brushes.White,FontSize=17,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center}},0,0);
 var commands=new StackPanel{Orientation=Orientation.Horizontal,Spacing=4};foreach(var label in new[]{"File","Edit","Tools","Options"}){var b=Button(label);b.Click+=(_,_)=>{if(label=="Tools" || label=="Options")ShowTool();else status.Text=label+" · Visual concept menu";};commands.Children.Add(b);}Put(menu,commands,1,0);var appearance=new StackPanel{Orientation=Orientation.Horizontal,Spacing=4,Margin=new(0,0,8,0)};var toolButton=Button("Preferences");toolButton.Click+=(_,_)=>ShowTool();appearance.Children.Add(toolButton);themeButton=Button("Dark mode");themeButton.Click+=(_,_)=>SetDark(!dark);appearance.Children.Add(themeButton);Put(menu,appearance,2,0);Put(root,menu,0,0);
 var file=new Grid{ColumnDefinitions=new("*,Auto"),Margin=new(17,0)};var fileLabel=new StackPanel{Orientation=Orientation.Horizontal,Spacing=10};fileLabel.Children.Add(T("Pokémon Scarlet",13,Ink,true));fileLabel.Children.Add(T("/",12,"#C0C1C8"));fileLabel.Children.Add(T("Patrik · Paldea",11,Muted));Put(file,fileLabel,0,0);var save=Button("Export save  ↗",true);save.Click+=(_,_)=>status.Text="Preview only · No save file is modified";Put(file,save,1,0);Put(root,new Border{Child=file,BorderBrush=B(Line),BorderThickness=new(0,1,0,1)},0,1);
 var body=new Grid{ColumnDefinitions=new("306,*")};Put(root,body,0,2);
 var editor=new Grid{RowDefinitions=new("94,36,*,40"),Margin=new(17,6,17,12)};var hero=new Grid{ColumnDefinitions=new("81,*")};Put(hero,portrait,0,0);var title=new StackPanel{Spacing=5,VerticalAlignment=VerticalAlignment.Center,Margin=new(10,0,0,0)};title.Children.Add(number);title.Children.Add(name);title.Children.Add(types);Put(hero,title,1,0);Put(editor,hero,0,0);
 var tabs=new Grid{ColumnDefinitions=new("*,*,*,*,*")};int col=0;foreach(var label in new[]{"Main","Stats","Moves","Met","OT"}){var b=Button(label);b.Padding=new(5,7);b.FontSize=11;b.Foreground=B(label=="Main"?Accent:Muted);b.Click+=(_,_)=>{tab=label;foreach(var c in tabs.Children.OfType<Button>())c.Foreground=B(Muted);b.Foreground=B(Accent);FillForm();};Put(tabs,b,col++,0);}Put(editor,new Border{Child=tabs,BorderBrush=B(Line),BorderThickness=new(0,0,0,1),Margin=new(0,0,0,10)},0,1);Put(editor,form,0,2);
 var editActions=new Grid{ColumnDefinitions=new("*,Auto,Auto")};Put(editActions,T("✓  Legal · sample",10,"#52836C"),0,0);var revert=Button("Reset");revert.Click+=(_,_)=>FillForm();Put(editActions,revert,1,0);var apply=Button("Apply",true);apply.Click+=(_,_)=>status.Text="Concept preview · Changes are not written to a save";Put(editActions,apply,2,0);Put(editor,editActions,0,3);Put(body,new Border{Child=editor,Background=B("#FFFFFF"),BorderBrush=B(Line),BorderThickness=new(0,0,1,0)},0,0);
 var boxArea=new Grid{RowDefinitions=new("39,*,24,72"),Margin=new(16,5,16,12)};var boxHeader=new Grid{ColumnDefinitions=new("Auto,*,Auto")};Put(boxHeader,T("BOX 01",10,Muted,true),0,0);var labelbox=new StackPanel{Orientation=Orientation.Horizontal,Spacing=10,Margin=new(13,0,0,0)};labelbox.Children.Add(T("Favorites",14,Ink,true));labelbox.Children.Add(T("24 / 30",10,Muted));Put(boxHeader,labelbox,1,0);Put(boxHeader,T("‹       ›",18,Muted),2,0);Put(boxArea,boxHeader,0,0);Put(boxArea,slots,0,1);
 var hint=new Grid{ColumnDefinitions=new("*,Auto")};Put(hint,T("Click a Pokémon to inspect",9,Muted),0,0);Put(hint,T("01   02   03   ···   32",10,Muted),1,0);Put(boxArea,hint,0,2);
 var party=new Grid{RowDefinitions=new("20,*"),Margin=new(0,6,0,0)};Put(party,T("PARTY",9,Muted,true),0,0);var members=new Grid{ColumnDefinitions=new("*,*,*,*,*,*")};for(int i=0;i<6;i++){int ix=i;var p=new Grid{ColumnDefinitions=new("*,Auto")};Put(p,Art(mons[i].id,36),0,0);Put(p,T(mons[i].level.ToString(),9,Muted),1,0);var b=new Button{Content=p,Padding=new(5,1),Background=B("#FFFFFF"),BorderBrush=B(Line),BorderThickness=new(1),CornerRadius=new(6),Margin=new(0,0,5,0),HorizontalAlignment=HorizontalAlignment.Stretch,HorizontalContentAlignment=HorizontalAlignment.Stretch};b.Click+=(_,_)=>Select(ix);Put(members,b,i,0);}Put(party,members,0,1);Put(boxArea,party,0,3);Put(body,boxArea,1,0);
 var foot=new Grid{ColumnDefinitions=new("*,Auto"),Margin=new(17,0)};Put(foot,status,0,0);Put(foot,T("900 × 600   /   Avalonia",9,Muted),1,0);Put(root,new Border{Child=foot,BorderBrush=B(Line),BorderThickness=new(0,1,0,0),Background=B("#FFFFFF")},0,3);
 Populate();FillForm();SetDark(true);Opened+=(_,_)=>{var timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(2)};timer.Tick+=(_,_)=>{timer.Stop();ShowTool();if(!Environment.GetCommandLineArgs().Contains("--capture"))return;CaptureWindow(this,"compact-dark.png");var second=new DispatcherTimer{Interval=TimeSpan.FromSeconds(1)};int stage=0;second.Tick+=(_,_)=>{if(stage++==0){CaptureWindow(toolWindow!,"preferences-dark.png");SetDark(false);}else if(stage==2){CaptureWindow(this,"compact-light.png");CaptureWindow(toolWindow!,"preferences-light.png");SetDark(true);second.Stop();}};second.Start();};timer.Start();};
 }
 void Populate(){slots.Children.Clear();for(int i=0;i<30;i++){int ix=i;var grid=new Grid{RowDefinitions=new("*,15")};if(i<mons.Length){Put(grid,Art(mons[i].id,47),0,0);var text=T(mons[i].name,9,Ink);text.HorizontalAlignment=HorizontalAlignment.Center;Put(grid,text,0,1);}else{var empty=T("·",20,"#CDD0D8");empty.HorizontalAlignment=HorizontalAlignment.Center;Put(grid,empty,0,0,2);}
 var b=new Button{Content=grid,Padding=new(2,2),Background=B(i==selected?"#F5E8EA":"#FFFFFF"),BorderBrush=B(i==selected?"#B66A73":Line),BorderThickness=new(1),CornerRadius=new(7),Margin=new(0,0,5,5),HorizontalAlignment=HorizontalAlignment.Stretch,VerticalAlignment=VerticalAlignment.Stretch,HorizontalContentAlignment=HorizontalAlignment.Stretch,VerticalContentAlignment=VerticalAlignment.Stretch};if(i<mons.Length)b.Click+=(_,_)=>Select(ix);Put(slots,b,i%6,i/6);}}
 void Select(int i){selected=i;var m=mons[i];name.Text=m.name;number.Text="#"+m.id.ToString("D4")+" · Lv. "+m.level;portrait.Source=Art(m.id,76).Source;types.Text=i==0?"PSYCHIC   /   FAIRY":"POKÉMON   /   SAMPLE";Populate();FillForm();}
 void FillForm(){form.Children.Clear();var m=mons[selected];if(tab=="Main") {Row("Species",m.name+"  ⌄");Row("Nickname",m.name);var twin=new Grid{ColumnDefinitions=new("*,12,*")};Put(twin,Field("Level",m.level.ToString()),0,0);Put(twin,Field("Nature",selected==0?"Modest  ⌄":"Adamant  ⌄"),2,0);form.Children.Add(twin);Row("Ability",selected==0?"Synchronize  ⌄":"Primary ability  ⌄");Row("Held item",selected==0?"Leftovers  ⌄":"None  ⌄");var small=new Grid{ColumnDefinitions=new("*,*")};Put(small,T("○  Normal coloration",10,Muted),0,0);Put(small,T("♀   Female",10,Muted),1,0);form.Children.Add(small);}
 else if(tab=="Stats"){form.Children.Add(T("STAT                IV          EV          TOTAL",10,Muted,true));var names=new[]{"HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"};var vals=new[]{"211","112","121","244","191","145"};for(int i=0;i<6;i++){var g=new Grid{ColumnDefinitions=new("*,45,45,45")};Put(g,T(names[i],11,Ink),0,0);Put(g,T("31",11,Muted),1,0);Put(g,T(i==3?"252":"0",11,Muted),2,0);Put(g,T(vals[i],11,Accent,true),3,0);form.Children.Add(new Border{Child=g,Padding=new(0,6),BorderBrush=B(Line),BorderThickness=new(0,0,0,1)});}}
 else if(tab=="Moves"){foreach(var move in new[]{"Moonblast","Psychic","Calm Mind","Protect"})Row("Move "+(form.Children.Count+1),move+"  ⌄");}
 else if(tab=="Met"){Row("Game","Pokémon Scarlet");Row("Location","South Province  ⌄");Row("Ball","Premier Ball  ⌄");Row("Met level","24");}
 else{Row("Original trainer","Patrik");Row("Trainer ID","123456");Row("Language","English  ⌄");Row("Friendship","255");}
 }
 void Row(string label,string value){var g=new Grid{ColumnDefinitions=new("71,*")};Put(g,T(label,11,Muted),0,0);Put(g,Input(value),1,0);form.Children.Add(g);}
 static StackPanel Field(string label,string value){var p=new StackPanel{Spacing=4};p.Children.Add(T(label,10,Muted));p.Children.Add(Input(value));return p;}
 static TextBox MakeTextInput(string value)=>new(){Text=value,FontSize=11,MinHeight=29,Height=29,Padding=new(9,5),CornerRadius=new(5),Background=B("#FBFBFC"),BorderBrush=B(Line),Foreground=B(Ink)};
 void Capture(){using var bitmap=new RenderTargetBitmap(new PixelSize((int)Bounds.Width,(int)Bounds.Height),new Vector(96,96));bitmap.Render((Visual)Content!);bitmap.Save(Path.Combine(AppContext.BaseDirectory,"compact-preview.png"));}
 static Image Art(int id,double height)=>new(){Source=new Bitmap(Path.Combine(AppContext.BaseDirectory,"Assets","a_"+id+".png")),Height=height,Stretch=Stretch.Uniform};
 static IBrush B(string s){if(!palette.TryGetValue(s,out var brush)){brush=new SolidColorBrush(Color.Parse(dark&&night.TryGetValue(s,out var mapped)?mapped:s));palette[s]=brush;}return brush;}
 void SetDark(bool enabled){dark=enabled;if(themeSelector!=null && (string?)themeSelector.SelectedItem!=(dark?"Dark":"Light"))themeSelector.SelectedItem=dark?"Dark":"Light";foreach(var (key,brush) in palette)brush.Color=Color.Parse(dark&&night.TryGetValue(key,out var mapped)?mapped:key);Application.Current!.RequestedThemeVariant=dark?ThemeVariant.Dark:ThemeVariant.Light;if(themeButton!=null)themeButton.Content=dark?"Light mode":"Dark mode";}
 static Control Input(string value){if(!value.Contains('⌄'))return MakeTextInput(value);var current=value.Replace("⌄","").Trim();string[] choices=current switch {"Modest" or "Adamant"=>["Modest","Adamant","Timid","Jolly","Calm","Bold"],"Synchronize" or "Primary ability"=>[current,"Trace","Telepathy"],"Leftovers" or "None"=>["None","Leftovers","Life Orb","Choice Specs","Focus Sash"],"Gardevoir"=>["Gardevoir","Kirlia","Ralts","Gallade"],"English"=>["English","Deutsch","Français","Italiano","日本語"],"Premier Ball"=>["Premier Ball","Poké Ball","Luxury Ball","Moon Ball"],"South Province"=>["South Province","North Province","Area Zero"],"Moonblast" or "Psychic" or "Calm Mind" or "Protect"=>["Moonblast","Psychic","Calm Mind","Protect","Shadow Ball"],_=>[current,"Alternate form"]};return Combo(choices,current);}
 static ComboBox Combo(string[] choices,string selected)=>new(){ItemsSource=choices,SelectedItem=selected,FontSize=11,MinHeight=29,Height=29,Padding=new(9,3),CornerRadius=new(5),Background=B("#FBFBFC"),BorderBrush=B(Line),Foreground=B(Ink),HorizontalAlignment=HorizontalAlignment.Stretch,MaxDropDownHeight=210};
 void ShowTool(){if(toolWindow!=null){toolWindow.Activate();return;}var panel=new Grid{Background=B(Paper),RowDefinitions=new("70,*,55")};var header=new StackPanel{Spacing=5,Margin=new(20,14)};header.Children.Add(T("Preferences",19,Ink,true));header.Children.Add(T("Make this workspace yours.",11,Muted));Put(panel,new Border{Child=header,Background=B("#FFFFFF"),BorderBrush=B(Line),BorderThickness=new(0,0,0,1)},0,0);
 var settings=new StackPanel{Spacing=16,Margin=new(20,16)};settings.Children.Add(T("APPEARANCE",10,Muted,true));var theme=Combo(["Light","Dark"],dark?"Dark":"Light");themeSelector=theme;theme.SelectionChanged+=(_,_)=>SetDark((string?)theme.SelectedItem=="Dark");settings.Children.Add(Labeled("Theme",theme));settings.Children.Add(Labeled("Accent",Combo(["Rose","Slate","Teal"],"Rose")));settings.Children.Add(Labeled("Sprite style",Combo(["Classic sprites","Artwork"],"Artwork")));settings.Children.Add(new Border{Height=1,Background=B(Line)});settings.Children.Add(T("EDITOR",10,Muted,true));settings.Children.Add(new CheckBox{Content="Show legality indicators",IsChecked=true,FontSize=11,Foreground=B(Ink),MinHeight=24});settings.Children.Add(new CheckBox{Content="Confirm before replacing a Pokémon",IsChecked=true,FontSize=11,Foreground=B(Ink),MinHeight=24});settings.Children.Add(T("Sample preferences · Theme changes are live.",10,Muted));Put(panel,settings,0,1);
 var footer=new Grid{ColumnDefinitions=new("*,Auto"),Margin=new(20,0)};Put(footer,T("Changes stay in this preview",10,Muted),0,0);var done=Button("Done",true);done.Click+=(_,_)=>toolWindow?.Close();Put(footer,done,1,0);Put(panel,new Border{Child=footer,BorderBrush=B(Line),BorderThickness=new(0,1,0,0),Background=B("#FFFFFF")},0,2);toolWindow=new Window{Title="Preferences · PKHeX concept",Width=390,Height=492,CanResize=false,Content=panel,Background=B(Paper),FontFamily=new("Inter"),WindowStartupLocation=WindowStartupLocation.Manual};toolWindow.Closed+=(_,_)=>{toolWindow=null;themeSelector=null;};toolWindow.Show(this);toolWindow.Position=new PixelPoint(Position.X+(int)(Width*RenderScaling)-100,Position.Y+65);}
 static Grid Labeled(string label,Control control){var g=new Grid{ColumnDefinitions=new("100,*")};Put(g,T(label,11,Ink),0,0);Put(g,control,1,0);return g;}
 static void CaptureWindow(Window window,string filename){using var bitmap=new RenderTargetBitmap(new PixelSize((int)window.Bounds.Width,(int)window.Bounds.Height),new Vector(96,96));bitmap.Render((Visual)window.Content!);bitmap.Save(Path.Combine(AppContext.BaseDirectory,filename));}

 static TextBlock T(string text,double size,string color,bool bold=false)=>new(){Text=text,FontSize=size,Foreground=B(color),FontWeight=bold?FontWeight.SemiBold:FontWeight.Regular,VerticalAlignment=VerticalAlignment.Center};
 static Button Button(string text,bool primary=false)=>new(){Content=text,Background=primary?B(Accent):Brushes.Transparent,Foreground=primary?Brushes.White:B(Ink),CornerRadius=new(5),Padding=new(11,6),FontSize=11,MinHeight=27,BorderThickness=new(0),VerticalAlignment=VerticalAlignment.Center};
 static void Put(Grid grid,Control child,int col,int row,int rows=1){Grid.SetColumn(child,col);Grid.SetRow(child,row);Grid.SetRowSpan(child,rows);grid.Children.Add(child);}
}
