<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/Gen5/DexBackground.bin" />
    <EmbeddedResource Include="Resources/Gen7Fashion/*.bin" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <ProjectReference Include="..\PKHeX.Core\PKHeX.Core.csproj" />
  </ItemGroup>
</Project>
